FranckKe/mersea

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
> [master] Add css for devise views

- app/models/tracer.rb
- db/migrate/20161008103028_create_tracers.rb
- db/schema.rb
Needs to run `bundle exec rake db:drop db:create db:migrate`
> Fix forbidden field name in Report

- app/assets/javascripts/utils.js
- app/assets/javascripts/views/pages_index.js
`http://localhost:3000//reports` is now `http://localhost:3000/reports`
> [master] Fix url formating in Ajax requests

- app/models/admin.rb
- app/models/concerns/admin_manager.rb
Resolve #58 
Resolve #59 
Resolve #60
> [master] Improved admin UI

- app/assets/javascripts/views/pages_index.js
> [master] Add marker count in legend

- app/assets/stylesheets/tracers/index.scss
> [master] Improve tracer list display

- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- config/initializers/devise_failure.rb
- docker-compose.yml
- dockerfiles/nginx.conf
Resolve #87 
Linked to #24 
```
docker build -t franckke/mersea .
docker-compose up
```
> [master] Docker ready

- app/controllers/reports_controller.rb
- app/views/reports/_edit.html.erb
- app/views/reports/_new.html.erb
Disable name editing if user is connected
Linked to #105
> [master] Fix reports creation

- Dockerfile
> [master] Docker multistage builds for lighter images

- Dockerfile
https://robots.thoughtbot.com/prevent-spoofing-with-paperclip
> [1.0] Fix Prevent Spoofing with Paperclip

- app/controllers/application_controller.rb
> [master] Fix admin redirect loop

- app/assets/javascripts/rails_admin/custom/ui.js
- app/assets/javascripts/rails_admin/ra.widgets.coffee
- app/assets/stylesheets/rails_admin/custom/theming.scss
- app/controllers/application_controller.rb
- app/models/concerns/page_manager.rb
- app/models/page.rb
- app/views/layouts/_topbar.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- db/migrate/20180327185859_add_language_to_pages.rb
- db/schema.rb
- db/seeds.rb
> [master] Add language to Page

- app/assets/javascripts/views/pages_index.js
- app/serializers/report_serializer.rb
Display quantity in report's popup
Display total quantity of reported tracer in legend instead of numbers of reports
> [master] Display quantity in popup and legend

- config/environments/production.rb
Fix according the last failed build https://hub.docker.com/r/franckke/mersea/builds/bwsb4txwbtpjfqtz3snwx9g/ and this issue https://github.com/lautis/uglifier/issues/127
> [master] Fix JS transpilation

- app/assets/javascripts/views/devise_password.js
- app/assets/javascripts/views/devise_registration.js
- app/assets/javascripts/views/devise_session.js
- app/assets/javascripts/views/reports_new.js
- app/assets/javascripts/views/users_me.js
- app/assets/stylesheets/base/helpers.scss
- app/assets/stylesheets/components/card.scss
- app/controllers/reports_controller.rb
- app/controllers/users_controller.rb
- app/views/devise/passwords/_edit.html.erb
- app/views/reports/_edit.html.erb
- app/views/reports/_new.html.erb
- app/views/reports/edit.js.erb
- app/views/tracers/index.html.erb
- app/views/users/me.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
Fix missing translation
Change few "témoignage" to "signalement" to be consistent
Change report's "date" to "date of report"
Add account creation indication around recaptcha when creating report
Add review indication when creating report
Fix loaders not being hidden in js
Fix reports creation redirection with local
> [master] Fix datepicker date format conflict with i18n

- app/mailers/postmark_devise_mailer.rb
- app/views/devise/passwords/edit.html.erb
- Fix `secrets.yml` parsing to symbolized Hash
- Fix i18n changes in reset password page
> [master] Fix mailer

- app/mersea-front/build/webpack.base.conf.js
- app/mersea-front/package.json
- app/mersea-front/src/App.vue
- app/mersea-front/src/components/Home.vue
- app/mersea-front/src/main.js
- app/mersea-front/yarn.lock
Add Mapbox map
- Add search bar
- Add geolocalization
- Add zoom
- Add scale
- Whitelist mapbox-gl from webpack
- Add topbar
- Add colors
> [pu-2.0] Tp mapbox

- app/mailers/postmark_devise_mailer.rb
- app/mersea-front/build/webpack.base.conf.js
- app/mersea-front/index.html
- app/mersea-front/package.json
- app/mersea-front/src/App.vue
- app/mersea-front/src/components/Home.vue
- app/mersea-front/src/main.js
- app/mersea-front/yarn.lock
- app/views/devise/passwords/edit.html.erb
* Implement Bulma nav bar menu
* Add hamburger and responsive capability
* Insert links to different pages
Changes will be needed depending on the colors we want to use
> [pu-2.0] Tp menu

- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/reports_controller.rb
- app/controllers/tracers_controller.rb
- app/controllers/users_controller.rb
- app/models/concerns/filterable.rb
- app/models/report.rb
- app/serializers/geojson_report_serializer.rb
- app/serializers/geojson_reports_serializer.rb
- app/serializers/report_serializer.rb
- app/views/layouts/_menu.html.erb
- config/application.rb
- config/initializers/devise.rb
- config/initializers/devise_failure.rb
- config/initializers/mime_types.rb
- config/routes.rb
> [pu-2.0] Geojson and Filtrable (3)

- app/models/concerns/report_manager.rb
Crash admin rail when viewing report(s)
> [pu-2.0] Fix admin reports email

- app/mersea-front/src/components/Home.vue
Errors are triggered by missing function on map hover
> [pu-2.0] Fix map mousemove errors

- app/controllers/users/sessions_controller.rb
> [pu-2.0] Fix sign out

- app/mersea-front/package.json
- app/mersea-front/src/App.vue
- app/mersea-front/src/components/Home.vue
- app/mersea-front/src/components/Leaderboard.vue
- app/mersea-front/src/components/Tracers.vue
- app/mersea-front/src/components/TracersGrid.vue
- app/mersea-front/src/components/TracersList.vue
- app/mersea-front/src/main.js
- app/mersea-front/src/router/index.js
- app/mersea-front/yarn.lock
- app/serializers/tracer_serializer.rb
- spec/serializers/tracer_serializer_spec.rb
- spec/support/api/schemas/tracer.json
- Tracers view (grid/list)
- Search bar
- Link each tracer to its tracer view
- Add "Tracers" link to home page
- Use FontAwesome npm module
> [pu-2.0] Tracers view

- app/assets/javascripts/views/pages_index.js
- config/locales/fr.yml
Allow satellite tiles with road information
Change 'Merci' to 'Mersea' when succesfull report
> [master] Use mapbox background

- app/assets/javascripts/application.js.erb
- app/assets/javascripts/rails_admin/custom/ui.js
- app/assets/javascripts/views/pages_index.js
- vendor/assets/javascripts/leaflet-tileborderfix.js
Add mapbox in /admin/report/:id
> [master] Add hack for tiles border

- frontend/src/App.vue
- frontend/src/components/TracersList.vue
- frontend/src/views/Tracers.vue
- Add transition to router view and tracer grid/list switch
- Fix tracer description width in list view
> [pu-2.0] Transitions

- app/models/concerns/page_manager.rb
- app/models/page.rb
- app/serializers/page_serializer.rb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- db/migrate/20180705223042_add_category_to_pages.rb
- db/schema.rb
- frontend/src/App.vue
- frontend/src/components/Menu.vue
- frontend/src/components/MenuNav.vue
- frontend/src/main.js
- frontend/src/router.js
- frontend/src/store.js
- frontend/src/views/Page.vue
- spec/models/page_spec.rb
- spec/support/api/schemas/page.json
> [pu-2.0] Add category to pages

- app/controllers/reports_controller.rb
- app/policies/report_policy.rb
> [pu-2.0] Pundit Scopes

- frontend/public/index.html
- frontend/public/manifest.json
Merge after  #182
Change app's title
> [pu-2.0] Fix app title - To merge after #182

- frontend/src/views/Leaderboard.vue
Merge after #182
Fix warning when navigating to leaderboard
> [pu-2.0] Fix leaderboard warning name

- frontend/src/components/AddReport.vue
- frontend/src/components/LangSwitcher.vue
- frontend/src/components/MenuNav.vue
- frontend/src/components/TracersGrid.vue
- frontend/src/components/TracersList.vue
- frontend/src/views/Leaderboard.vue
- frontend/src/views/Login.vue
- frontend/src/views/Page.vue
- frontend/src/views/Register.vue
- frontend/src/views/Tracers.vue
Merge after #182
Scope css to component/view
> [pu-2.0] Use scoped style

- frontend/src/components/MenuNav.vue
- frontend/src/store/modules/addReport.js
To merge after #182 
Bug: 
Clicking on `login` `register` or `me` append on current url, breaking navigation from subpages
> [pu-2.0] Fix navbar router navigation

- frontend/src/App.vue
- frontend/src/components/AddReport.vue
- frontend/src/components/MenuNav.vue
- frontend/src/store/index.js
- frontend/src/store/modules/pages.js
- frontend/src/store/modules/reports.js
- frontend/src/store/modules/tracers.js
- frontend/src/views/Home.vue
- frontend/src/views/Leaderboard.vue
- frontend/src/views/Register.vue
- frontend/src/views/Tracers.vue
Sometimes data does not load correctly (see alpha). This refactor should fix this.
Additional fixes:
- Adjust margin for input file error message
- Fix address input not being disabled
> [pu-2.0] Refactor async actions

- frontend/src/components/TracersGrid.vue
- frontend/src/components/TracersList.vue
Remove link to /tracers/:id
Fix images
Adjust columns width
- 1/3 desktop
- 1/2 tablet
- full mobile
> [pu-2.0] Improve tracer grid list view

- frontend/src/components/AddReport.vue
- frontend/src/main.js
- frontend/src/views/Home.vue
Also fix responsive map height
> [pu-2.0] Add close buttons to add report form and fix responsive height

- frontend/src/main.js
- frontend/src/views/Me.vue
- frontend/yarn.lock
Add forms to update account information in `/me`
> [pu-2.0] Add user update form

- frontend/src/components/AddReport.vue
Fix #210 
Username field is populated and disabled if a user is logged in
Photo field is removed if the user logged in is senior
> [pu-2.0] Add logged in username and senior photo check

- frontend/src/components/AddReport.vue
- frontend/src/components/LangSwitcher.vue
- frontend/src/views/Login.vue
- frontend/src/views/Register.vue
Add field translation in v-validate errors
Before:
`Le champ password doit contenir au minimum 6 caractères.`
After:
`Le champ mot de passe doit contenir au minimum 6 caractères.`
> [pu-2.0] I18n v-validate error messages

- frontend/src/components/AddReport.vue
> Fix step reset on finish close

- frontend/src/store/modules/reports.js
- frontend/src/views/Home.vue
- Move geojson fetch after mapbox initialisation and before map logic initialisation
- Add loader over the map while data is getting fetch
- Add error toast if the data fetching fail
- Order functions by their order
> [pu-2.0] Tp refactor home

- frontend/src/views/Home.vue
> [pu-2.0] Tweak map cluster style

- lib/mersea/errors.rb
- spec/requests/api_spec.rb
> [pu-2.0] Fix PG::DatetimeFieldOverflow error

- frontend/src/components/AddReport.vue
> Bulk report submission

- frontend/src/App.vue
- frontend/src/components/AddReport.vue
- frontend/src/components/MenuNav.vue
- frontend/src/components/Tool.vue
- frontend/src/components/ToolBar.vue
- frontend/src/components/tools/FilterReports.vue
- frontend/src/main.js
- frontend/src/store/index.js
- frontend/src/store/modules/reports.js
- frontend/src/store/modules/toolBar.js
- frontend/src/store/modules/tracers.js
- frontend/src/views/Home.vue
- frontend/src/views/Tracers.vue
Add report as tool to be developped after bulk report
> Add filter tool

- frontend/src/components/MenuNav.vue
> Fix menunav links

- db/migrate/20180719220842_add_slug_to_pages.rb
> [pu-2.0] Fix slug migration

- app/controllers/reports_controller.rb
- frontend/src/components/AddReport.vue
Fix to 4 decimals when sending and receiving a new report request
> Fix coordinates decimals

- frontend/public/index.html
- frontend/src/components/AddReport.vue
- frontend/src/components/MenuNav.vue
- frontend/src/components/ToolBar.vue
- frontend/src/views/Tracers.vue
Fix tracer i18n
Fix manifest url
Fix favicon url
Fix file input layout issue with sentence
Scroll top in Step 2 of addreport to show errors
> [master] Fix analytics url + qol improvements

- frontend/src/components/AddReport.vue
- frontend/src/views/Home.vue
> Adds a geolocation button to AddReport

- frontend/src/components/AddReport.vue
- frontend/src/components/MenuNav.vue
- frontend/src/components/ToolBar.vue
- frontend/src/components/tools/FilterReportsByDate.vue
- frontend/src/components/tools/FilterReportsByTracer.vue
- frontend/src/components/tools/Information.vue
- frontend/src/main.js
- frontend/src/store/modules/pages.js
- frontend/src/store/modules/toolBar.js
- frontend/src/store/modules/tracers.js
- frontend/src/views/Home.vue
- frontend/src/views/MyReports.vue
- frontend/src/views/Tracers.vue
By dispatching actions on app initialization instead of in components
creation
Add loader to each tool
Move map loader in map instead of overlapping map + toolbar
Add filter information on filter tracer tool
Add loader to /tracers
Typo
> Optimize state initialization

- frontend/src/components/TracersGrid.vue
- frontend/src/components/TracersList.vue
- frontend/src/views/Tracers.vue
Add tracer sort on grid view
Tracer grid card equal height
Sorting is reset on search
> Add tracer sort on grid view

- frontend/src/components/MenuNav.vue
- frontend/src/components/tools/FilterReportsByTracer.vue
- frontend/src/main.js
- frontend/src/store/modules/pages.js
- frontend/src/store/modules/reports.js
- frontend/src/store/modules/tracers.js
- frontend/src/views/Home.vue
Fix reports/map loading race
Remove useless loadPage
> Fix reports/map loading race

- Dockerfile
- app/models/concerns/tracer_manager.rb
- app/models/tracer.rb
- app/serializers/tracer_serializer.rb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- db/migrate/20190526083946_add_category_to_tracers.rb
- db/schema.rb
- db/seeds.rb.bak
- frontend/src/components/AddReport.vue
- frontend/src/components/TracerCard.vue
- frontend/src/components/TracersGrid.vue
- frontend/src/components/TracersList.vue
- frontend/src/components/tools/FilterReportsByTracer.vue
- frontend/src/store/modules/tracers.js
- spec/factories/tracer.rb
- spec/models/tracer_spec.rb
- spec/serializers/tracer_serializer_spec.rb
- spec/support/api/schemas/tracer.json
Add category to tracers (drifting, containers, research, archive)
> Add tracer category

- frontend/src/components/ToolBar.vue
- frontend/src/components/TracersGrid.vue
- frontend/src/components/tools/FilterReportsByTracer.vue
- frontend/src/views/Home.vue
Expand reports on same position
> Spiderify cluster

- frontend/src/components/Tool.vue
- frontend/src/components/ToolBar.vue
- frontend/src/components/tools/AddReport.vue
- frontend/src/store/modules/addReport.js
- frontend/src/views/Home.vue
- frontend/src/views/Register.vue
- frontend/yarn.lock
Remove 2 steps
Hide unused inputs
Use inline calendar
> Simplify add report

- frontend/src/views/Home.vue
Refactor and increase zoom range
> Fix addreport marker add on cluster number

- frontend/src/components/tools/AddReport.vue
Fix add report success message appearing even on report upload failing
Fix start of the week detection
> Fix addreport success message

- frontend/babel.config.js
- frontend/package.json
- frontend/src/components/MenuNav.vue
- frontend/src/components/tools/AddReport.vue
- frontend/src/components/tools/FilterReportsByDate.vue
- frontend/src/main.js
- frontend/src/store/modules/reports.js
Import all polyfill instead of trying to detect and then import
Tweak add report ui
Close opened tools when opening menu on mobile
Calculate report count * report quantity instead of just report count
> Import polyfills for older browser

- app/views/devise/sessions/new.html.erb
- config/initializers/devise.rb
- config/initializers/session_store.rb
Default to remember me for admin sessions
> Set session length to 3 months

- frontend/src/App.vue
- frontend/src/components/Tool.vue
- frontend/src/components/tools/AddReport.vue
Fix nav menu width initialization
Add information to get started on add report
Move account creation information to bottom
Add placeholder to search tracers input
Improve contrast on disabled address input
Tweak some french i18n
> Fix scrolling on tool view on small screen

- frontend/src/components/tools/AddReport.vue
Leftover from the time we had more than 2 steps.
> Prevent reports submission loop

- app/contexts/uploads.rb
- config/initializers/filter_parameter_logging.rb
- lib/tasks/diet_photo.rake
> [master] Apply a diet on uploaded images

- app/models/concerns/report_manager.rb
- app/models/report.rb
- db/migrate/20210406202836_remove_photo_for_rejected_reports.rb
- db/schema.rb
> Remove rejected photo

- .github/workflows/docker.yml
- .github/workflows/test.yml
- README.md
We have to setup the following secrets in the project in order to push the docker image on Docker hub:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN
> Github Actions

- LICENSE
- app/controllers/api_controller.rb
> Revert "Workaround HEAD /status"
